# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 
#
# Created: Sun May  3 12:07:39 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(820, 455)
        Form.setStyleSheet(_fromUtf8(""))
        self.lineEditChemin = QtGui.QLineEdit(Form)
        self.lineEditChemin.setGeometry(QtCore.QRect(375, 125, 436, 21))
        self.lineEditChemin.setObjectName(_fromUtf8("lineEditChemin"))
        self.textEdit = QtGui.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(375, 180, 431, 231))
        self.textEdit.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.pushButtonNouveau = QtGui.QPushButton(Form)
        self.pushButtonNouveau.setGeometry(QtCore.QRect(375, 155, 86, 21))
        self.pushButtonNouveau.setObjectName(_fromUtf8("pushButtonNouveau"))
        self.pushButtonOuvrir = QtGui.QPushButton(Form)
        self.pushButtonOuvrir.setGeometry(QtCore.QRect(465, 155, 85, 21))
        self.pushButtonOuvrir.setObjectName(_fromUtf8("pushButtonOuvrir"))
        self.pushButtonEnregistrer = QtGui.QPushButton(Form)
        self.pushButtonEnregistrer.setGeometry(QtCore.QRect(555, 155, 86, 21))
        self.pushButtonEnregistrer.setObjectName(_fromUtf8("pushButtonEnregistrer"))
        self.pushButtonEnvoiGCode = QtGui.QPushButton(Form)
        self.pushButtonEnvoiGCode.setGeometry(QtCore.QRect(650, 155, 136, 21))
        self.pushButtonEnvoiGCode.setObjectName(_fromUtf8("pushButtonEnvoiGCode"))
        self.line_5 = QtGui.QFrame(Form)
        self.line_5.setGeometry(QtCore.QRect(370, 110, 436, 16))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.labelTraceEnvoiSerie = QtGui.QLabel(Form)
        self.labelTraceEnvoiSerie.setGeometry(QtCore.QRect(10, 140, 191, 16))
        self.labelTraceEnvoiSerie.setObjectName(_fromUtf8("labelTraceEnvoiSerie"))
        self.labelFinLigne = QtGui.QLabel(Form)
        self.labelFinLigne.setGeometry(QtCore.QRect(140, 50, 101, 16))
        self.labelFinLigne.setObjectName(_fromUtf8("labelFinLigne"))
        self.comboBoxDebit = QtGui.QComboBox(Form)
        self.comboBoxDebit.setGeometry(QtCore.QRect(140, 25, 121, 24))
        self.comboBoxDebit.setObjectName(_fromUtf8("comboBoxDebit"))
        self.comboBoxDebit.addItem(_fromUtf8(""))
        self.comboBoxDebit.addItem(_fromUtf8(""))
        self.comboBoxDebit.addItem(_fromUtf8(""))
        self.comboBoxDebit.addItem(_fromUtf8(""))
        self.comboBoxDebit.addItem(_fromUtf8(""))
        self.comboBoxDebit.addItem(_fromUtf8(""))
        self.comboBoxDebit.addItem(_fromUtf8(""))
        self.comboBoxDebit.addItem(_fromUtf8(""))
        self.textEditReception = QtGui.QTextEdit(Form)
        self.textEditReception.setGeometry(QtCore.QRect(370, 30, 441, 81))
        self.textEditReception.setStyleSheet(_fromUtf8("background-color: rgb(244, 255, 190);"))
        self.textEditReception.setObjectName(_fromUtf8("textEditReception"))
        self.line_2 = QtGui.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(10, 130, 348, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.comboBoxFinLigne = QtGui.QComboBox(Form)
        self.comboBoxFinLigne.setGeometry(QtCore.QRect(140, 65, 121, 24))
        self.comboBoxFinLigne.setObjectName(_fromUtf8("comboBoxFinLigne"))
        self.comboBoxFinLigne.addItem(_fromUtf8(""))
        self.comboBoxFinLigne.addItem(_fromUtf8(""))
        self.comboBoxFinLigne.addItem(_fromUtf8(""))
        self.comboBoxFinLigne.addItem(_fromUtf8(""))
        self.pushButtonEnvoi = QtGui.QPushButton(Form)
        self.pushButtonEnvoi.setGeometry(QtCore.QRect(270, 101, 85, 33))
        self.pushButtonEnvoi.setObjectName(_fromUtf8("pushButtonEnvoi"))
        self.spinBoxDelaiReception = QtGui.QSpinBox(Form)
        self.spinBoxDelaiReception.setGeometry(QtCore.QRect(10, 70, 71, 23))
        self.spinBoxDelaiReception.setMaximum(10000)
        self.spinBoxDelaiReception.setProperty("value", 10)
        self.spinBoxDelaiReception.setObjectName(_fromUtf8("spinBoxDelaiReception"))
        self.comboBoxPort = QtGui.QComboBox(Form)
        self.comboBoxPort.setGeometry(QtCore.QRect(10, 25, 121, 24))
        self.comboBoxPort.setEditable(True)
        self.comboBoxPort.setObjectName(_fromUtf8("comboBoxPort"))
        self.comboBoxPort.addItem(_fromUtf8(""))
        self.comboBoxPort.addItem(_fromUtf8(""))
        self.comboBoxPort.addItem(_fromUtf8(""))
        self.comboBoxPort.addItem(_fromUtf8(""))
        self.labelDebit = QtGui.QLabel(Form)
        self.labelDebit.setGeometry(QtCore.QRect(140, 10, 131, 16))
        self.labelDebit.setObjectName(_fromUtf8("labelDebit"))
        self.line_3 = QtGui.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(357, 5, 16, 441))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.textEditTraceEnvoiSerie = QtGui.QTextEdit(Form)
        self.textEditTraceEnvoiSerie.setGeometry(QtCore.QRect(2, 160, 359, 70))
        self.textEditTraceEnvoiSerie.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);\n"
"background-color: rgb(170, 255, 255);"))
        self.textEditTraceEnvoiSerie.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.textEditTraceEnvoiSerie.setObjectName(_fromUtf8("textEditTraceEnvoiSerie"))
        self.pushButtonInitSerial = QtGui.QPushButton(Form)
        self.pushButtonInitSerial.setGeometry(QtCore.QRect(270, 10, 41, 41))
        self.pushButtonInitSerial.setObjectName(_fromUtf8("pushButtonInitSerial"))
        self.labelChaineEnvoi = QtGui.QLabel(Form)
        self.labelChaineEnvoi.setGeometry(QtCore.QRect(10, 95, 121, 16))
        self.labelChaineEnvoi.setObjectName(_fromUtf8("labelChaineEnvoi"))
        self.labelReception = QtGui.QLabel(Form)
        self.labelReception.setGeometry(QtCore.QRect(380, 10, 171, 16))
        self.labelReception.setObjectName(_fromUtf8("labelReception"))
        self.labelDelaiRecept = QtGui.QLabel(Form)
        self.labelDelaiRecept.setGeometry(QtCore.QRect(10, 50, 121, 16))
        self.labelDelaiRecept.setObjectName(_fromUtf8("labelDelaiRecept"))
        self.lineEditChaineEnvoi = QtGui.QLineEdit(Form)
        self.lineEditChaineEnvoi.setGeometry(QtCore.QRect(10, 110, 255, 23))
        self.lineEditChaineEnvoi.setText(_fromUtf8(""))
        self.lineEditChaineEnvoi.setObjectName(_fromUtf8("lineEditChaineEnvoi"))
        self.pushButtonStop = QtGui.QPushButton(Form)
        self.pushButtonStop.setGeometry(QtCore.QRect(310, 10, 41, 41))
        self.pushButtonStop.setObjectName(_fromUtf8("pushButtonStop"))
        self.labelPort = QtGui.QLabel(Form)
        self.labelPort.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.labelPort.setObjectName(_fromUtf8("labelPort"))
        self.pushButtonPassGCode = QtGui.QPushButton(Form)
        self.pushButtonPassGCode.setGeometry(QtCore.QRect(380, 420, 61, 27))
        self.pushButtonPassGCode.setObjectName(_fromUtf8("pushButtonPassGCode"))
        self.pushButtonStopGCode = QtGui.QPushButton(Form)
        self.pushButtonStopGCode.setGeometry(QtCore.QRect(450, 420, 61, 27))
        self.pushButtonStopGCode.setObjectName(_fromUtf8("pushButtonStopGCode"))
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(3, 234, 358, 217))
        self.label.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255,255);"))
        self.label.setText(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        self.line_8 = QtGui.QFrame(Form)
        self.line_8.setGeometry(QtCore.QRect(5, 338, 234, 16))
        self.line_8.setStyleSheet(_fromUtf8("background-color: rgba(255, 0, 0, 127);"))
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.pushButton_HOME_X = QtGui.QPushButton(Form)
        self.pushButton_HOME_X.setGeometry(QtCore.QRect(18, 273, 65, 27))
        self.pushButton_HOME_X.setStyleSheet(_fromUtf8("background-color: rgba(255, 0, 0, 127);"))
        self.pushButton_HOME_X.setObjectName(_fromUtf8("pushButton_HOME_X"))
        self.pushButton_HOME_Y = QtGui.QPushButton(Form)
        self.pushButton_HOME_Y.setGeometry(QtCore.QRect(161, 273, 65, 27))
        self.pushButton_HOME_Y.setStyleSheet(_fromUtf8("background-color: rgba(0, 255, 0, 127);"))
        self.pushButton_HOME_Y.setObjectName(_fromUtf8("pushButton_HOME_Y"))
        self.pushButton_HOME_Z = QtGui.QPushButton(Form)
        self.pushButton_HOME_Z.setGeometry(QtCore.QRect(293, 275, 65, 27))
        self.pushButton_HOME_Z.setStyleSheet(_fromUtf8("background-color: rgba(0, 160, 255, 255);"))
        self.pushButton_HOME_Z.setObjectName(_fromUtf8("pushButton_HOME_Z"))
        self.pushButton_RAZ_Z = QtGui.QPushButton(Form)
        self.pushButton_RAZ_Z.setGeometry(QtCore.QRect(292, 334, 65, 27))
        self.pushButton_RAZ_Z.setStyleSheet(_fromUtf8("background-color: rgba(0, 255, 255, 255);"))
        self.pushButton_RAZ_Z.setObjectName(_fromUtf8("pushButton_RAZ_Z"))
        self.pushButton_X_PLUS_UN = QtGui.QPushButton(Form)
        self.pushButton_X_PLUS_UN.setGeometry(QtCore.QRect(144, 332, 41, 27))
        self.pushButton_X_PLUS_UN.setStyleSheet(_fromUtf8("background-color: rgba(255, 0, 0, 200);"))
        self.pushButton_X_PLUS_UN.setObjectName(_fromUtf8("pushButton_X_PLUS_UN"))
        self.pushButton_X_PLUS_DIX = QtGui.QPushButton(Form)
        self.pushButton_X_PLUS_DIX.setGeometry(QtCore.QRect(194, 332, 41, 27))
        self.pushButton_X_PLUS_DIX.setStyleSheet(_fromUtf8("background-color: rgba(255, 0, 0, 200);"))
        self.pushButton_X_PLUS_DIX.setObjectName(_fromUtf8("pushButton_X_PLUS_DIX"))
        self.pushButton_X_MOINS_UN = QtGui.QPushButton(Form)
        self.pushButton_X_MOINS_UN.setGeometry(QtCore.QRect(60, 332, 41, 27))
        self.pushButton_X_MOINS_UN.setStyleSheet(_fromUtf8("background-color: rgba(255, 0, 0, 200);"))
        self.pushButton_X_MOINS_UN.setObjectName(_fromUtf8("pushButton_X_MOINS_UN"))
        self.pushButton_X_MOINS_DIX = QtGui.QPushButton(Form)
        self.pushButton_X_MOINS_DIX.setGeometry(QtCore.QRect(10, 333, 41, 27))
        self.pushButton_X_MOINS_DIX.setStyleSheet(_fromUtf8("background-color: rgba(255, 0, 0, 200);"))
        self.pushButton_X_MOINS_DIX.setObjectName(_fromUtf8("pushButton_X_MOINS_DIX"))
        self.line_6 = QtGui.QFrame(Form)
        self.line_6.setGeometry(QtCore.QRect(117, 253, 16, 191))
        self.line_6.setStyleSheet(_fromUtf8("background-color: rgba(0, 255, 0, 127);\n"
""))
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setLineWidth(2)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.pushButton_Y_PLUS_UN = QtGui.QPushButton(Form)
        self.pushButton_Y_PLUS_UN.setGeometry(QtCore.QRect(105, 300, 41, 27))
        self.pushButton_Y_PLUS_UN.setStyleSheet(_fromUtf8("background-color: rgba(0, 255, 0, 200);"))
        self.pushButton_Y_PLUS_UN.setObjectName(_fromUtf8("pushButton_Y_PLUS_UN"))
        self.pushButton_Y_MOINS_DIX = QtGui.QPushButton(Form)
        self.pushButton_Y_MOINS_DIX.setGeometry(QtCore.QRect(105, 410, 41, 27))
        self.pushButton_Y_MOINS_DIX.setStyleSheet(_fromUtf8("background-color: rgba(0, 255, 0, 200);"))
        self.pushButton_Y_MOINS_DIX.setObjectName(_fromUtf8("pushButton_Y_MOINS_DIX"))
        self.pushButton_Y_MOINS_UN = QtGui.QPushButton(Form)
        self.pushButton_Y_MOINS_UN.setGeometry(QtCore.QRect(105, 370, 41, 27))
        self.pushButton_Y_MOINS_UN.setStyleSheet(_fromUtf8("background-color: rgba(0, 255, 0, 200);"))
        self.pushButton_Y_MOINS_UN.setObjectName(_fromUtf8("pushButton_Y_MOINS_UN"))
        self.pushButton_Y_PLUS_DIX = QtGui.QPushButton(Form)
        self.pushButton_Y_PLUS_DIX.setGeometry(QtCore.QRect(105, 260, 41, 27))
        self.pushButton_Y_PLUS_DIX.setStyleSheet(_fromUtf8("background-color: rgba(0, 255, 0, 200);"))
        self.pushButton_Y_PLUS_DIX.setObjectName(_fromUtf8("pushButton_Y_PLUS_DIX"))
        self.line_7 = QtGui.QFrame(Form)
        self.line_7.setGeometry(QtCore.QRect(255, 243, 16, 204))
        self.line_7.setStyleSheet(_fromUtf8("background-color: rgba(0, 160, 255, 160);"))
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setLineWidth(2)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.pushButton_Z_MOINS_DIX = QtGui.QPushButton(Form)
        self.pushButton_Z_MOINS_DIX.setGeometry(QtCore.QRect(244, 417, 41, 27))
        self.pushButton_Z_MOINS_DIX.setStyleSheet(_fromUtf8("background-color: rgba(0, 160, 255, 255);"))
        self.pushButton_Z_MOINS_DIX.setObjectName(_fromUtf8("pushButton_Z_MOINS_DIX"))
        self.pushButton_Z_PLUS_UN = QtGui.QPushButton(Form)
        self.pushButton_Z_PLUS_UN.setGeometry(QtCore.QRect(244, 277, 41, 27))
        self.pushButton_Z_PLUS_UN.setStyleSheet(_fromUtf8("background-color: rgba(0, 160, 255, 255);"))
        self.pushButton_Z_PLUS_UN.setObjectName(_fromUtf8("pushButton_Z_PLUS_UN"))
        self.pushButton_Z_MOINS_ZERO_UN = QtGui.QPushButton(Form)
        self.pushButton_Z_MOINS_ZERO_UN.setGeometry(QtCore.QRect(244, 357, 41, 27))
        self.pushButton_Z_MOINS_ZERO_UN.setStyleSheet(_fromUtf8("background-color: rgba(0, 160, 255, 255);"))
        self.pushButton_Z_MOINS_ZERO_UN.setObjectName(_fromUtf8("pushButton_Z_MOINS_ZERO_UN"))
        self.pushButton_Z_MOINS_UN = QtGui.QPushButton(Form)
        self.pushButton_Z_MOINS_UN.setGeometry(QtCore.QRect(244, 387, 41, 27))
        self.pushButton_Z_MOINS_UN.setStyleSheet(_fromUtf8("background-color: rgba(0, 160, 255, 255);"))
        self.pushButton_Z_MOINS_UN.setObjectName(_fromUtf8("pushButton_Z_MOINS_UN"))
        self.pushButton_Z_PLUS_ZERO_UN = QtGui.QPushButton(Form)
        self.pushButton_Z_PLUS_ZERO_UN.setGeometry(QtCore.QRect(244, 307, 41, 27))
        self.pushButton_Z_PLUS_ZERO_UN.setStyleSheet(_fromUtf8("background-color: rgba(0, 160, 255, 255);"))
        self.pushButton_Z_PLUS_ZERO_UN.setObjectName(_fromUtf8("pushButton_Z_PLUS_ZERO_UN"))
        self.pushButton_Z_PLUS_DIX = QtGui.QPushButton(Form)
        self.pushButton_Z_PLUS_DIX.setGeometry(QtCore.QRect(244, 247, 41, 27))
        self.pushButton_Z_PLUS_DIX.setStyleSheet(_fromUtf8("background-color: rgba(0, 160, 255, 255);"))
        self.pushButton_Z_PLUS_DIX.setObjectName(_fromUtf8("pushButton_Z_PLUS_DIX"))

        self.retranslateUi(Form)
        self.comboBoxFinLigne.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "PyQt : CNC GCode GUI ", None))
        self.pushButtonNouveau.setText(_translate("Form", "Nouveau", None))
        self.pushButtonOuvrir.setText(_translate("Form", "Ouvrir", None))
        self.pushButtonEnregistrer.setText(_translate("Form", "Enregistrer", None))
        self.pushButtonEnvoiGCode.setText(_translate("Form", "Envoyer GCode", None))
        self.labelTraceEnvoiSerie.setText(_translate("Form", "Envoi sur le port série : ", None))
        self.labelFinLigne.setText(_translate("Form", "Fin de ligne :", None))
        self.comboBoxDebit.setItemText(0, _translate("Form", "115200", None))
        self.comboBoxDebit.setItemText(1, _translate("Form", "57600", None))
        self.comboBoxDebit.setItemText(2, _translate("Form", "38400", None))
        self.comboBoxDebit.setItemText(3, _translate("Form", "28800", None))
        self.comboBoxDebit.setItemText(4, _translate("Form", "19200", None))
        self.comboBoxDebit.setItemText(5, _translate("Form", "14400", None))
        self.comboBoxDebit.setItemText(6, _translate("Form", "9600", None))
        self.comboBoxDebit.setItemText(7, _translate("Form", "4800", None))
        self.comboBoxFinLigne.setItemText(0, _translate("Form", "Rien", None))
        self.comboBoxFinLigne.setItemText(1, _translate("Form", "Saut de ligne (\\n = LF)", None))
        self.comboBoxFinLigne.setItemText(2, _translate("Form", "Retour Chariot (\\r = CR)", None))
        self.comboBoxFinLigne.setItemText(3, _translate("Form", "Les 2 (LF + CR)", None))
        self.pushButtonEnvoi.setText(_translate("Form", "Envoi", None))
        self.comboBoxPort.setItemText(0, _translate("Form", "/dev/ttyACM0", None))
        self.comboBoxPort.setItemText(1, _translate("Form", "/dev/ttyACM1", None))
        self.comboBoxPort.setItemText(2, _translate("Form", "/dev/ttyUSB0", None))
        self.comboBoxPort.setItemText(3, _translate("Form", "/dev/ttyUSB1", None))
        self.labelDebit.setText(_translate("Form", "Débit Série (bauds) :", None))
        self.pushButtonInitSerial.setText(_translate("Form", "Init", None))
        self.labelChaineEnvoi.setText(_translate("Form", "Chaîne à envoyer :", None))
        self.labelReception.setText(_translate("Form", "Réception sur le port série : ", None))
        self.labelDelaiRecept.setText(_translate("Form", "Délai Récept. (ms)", None))
        self.pushButtonStop.setText(_translate("Form", "Stop", None))
        self.labelPort.setText(_translate("Form", "Port Série :", None))
        self.pushButtonPassGCode.setText(_translate("Form", "Pass", None))
        self.pushButtonStopGCode.setText(_translate("Form", "STOP", None))
        self.pushButton_HOME_X.setText(_translate("Form", "Home X", None))
        self.pushButton_HOME_Y.setText(_translate("Form", "Home Y", None))
        self.pushButton_HOME_Z.setText(_translate("Form", "Home Z", None))
        self.pushButton_RAZ_Z.setText(_translate("Form", "RAZ Z", None))
        self.pushButton_X_PLUS_UN.setText(_translate("Form", "+1", None))
        self.pushButton_X_PLUS_DIX.setText(_translate("Form", "+10", None))
        self.pushButton_X_MOINS_UN.setText(_translate("Form", "-1", None))
        self.pushButton_X_MOINS_DIX.setText(_translate("Form", "-10", None))
        self.pushButton_Y_PLUS_UN.setText(_translate("Form", "+1", None))
        self.pushButton_Y_MOINS_DIX.setText(_translate("Form", "-10", None))
        self.pushButton_Y_MOINS_UN.setText(_translate("Form", "-1", None))
        self.pushButton_Y_PLUS_DIX.setText(_translate("Form", "+10", None))
        self.pushButton_Z_MOINS_DIX.setText(_translate("Form", "-10", None))
        self.pushButton_Z_PLUS_UN.setText(_translate("Form", "+1", None))
        self.pushButton_Z_MOINS_ZERO_UN.setText(_translate("Form", "-0.1", None))
        self.pushButton_Z_MOINS_UN.setText(_translate("Form", "-1", None))
        self.pushButton_Z_PLUS_ZERO_UN.setText(_translate("Form", "+0.1", None))
        self.pushButton_Z_PLUS_DIX.setText(_translate("Form", "+10", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

